server:
  port: 8081

database:
  path: ":memory:"

cors:
  allowedOrigins:
    - "http://localhost:3000"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowedHeaders:
    - "Origin"
    - "Content-Type" 